<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>D4Scanner</AssemblyName>
    <RootNamespace>D4Scanner.App</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\D4Scanner.Core\D4Scanner.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\Fonts\Cinzel.ttf" />
  </ItemGroup>
</Project>
